---
title: "Répartition des milliardaires dans le monde"
author: "Marco Orfao"
---

# Répartition des milliardaires dans le monde

## Initialisation des bibliothèques et chargement des données

```{r}

# Chargement des bibliothèques principales
library(ggplot2)
library(tidyverse)
library(dplyr)

# Chargement des bibliothèques pour la géocodification et les données géographiques
library(tidygeocoder)
library(sf)
library(rnaturalearth)

world <- ne_countries(scale = "medium", returnclass = "sf")

# Chargement du dataset
dataset <- read.csv("./data/Billionaires_Statistics_Dataset.csv")

```

## Préparation des données (filtres et géocodification)


```{r}

# Filtrage des données pour ne conserver que les villes et pays valides
# Compte le nombre de milliardaires par ville pour former des groupes uniques
villes <- dataset %>% filter(
    !is.na(city), city != "",
    !is.na(country), country != ""
  ) %>% count(city, country, sort = TRUE)

# Géocodification des villes pour obtenir les coordonnées (latitude et longitude)
villes_geo <- villes %>%
  mutate(location = paste(city, country, sep = ", ")) %>%
  geocode(location, method = "osm", lat = lat, long = lon) %>%
  # Filtrage pour ne conserver que les villes trouvées
  filter(!is.na(lat), !is.na(lon))
```


## Paramétrage du diagramme et sauvegarde de l'image

```{r}
diagramme <- ggplot() +
  geom_sf(data = world, fill = "white", color = "grey80") +
  geom_point(
    data = villes_geo,
    aes(x = lon, y = lat, size = n),
    color = "darkblue",
    alpha = 0.7
  ) +
  scale_size(
    name = "Nombre de milliardaires",
    range = c(0.1, 3),
    trans = "log",
    breaks = c(1,4,8,16,32, 64),
    labels = c("1", "4", "8", "16", "32", "64+")
  ) +
  labs(title = "Répartition des milliardaires dans le monde") +
  theme_void()


diagramme

ggsave("map.png", diagramme, width = 10, height = 6, bg = "white")
```